version: "3.4"
services:
  sonardb:
    image: mysql/mysql-server
    volumes:
     - mysql_db:/var/lib/mysql
    command: --max_allowed_packet=256M
    environment:
     - MYSQL_ROOT_PASSWORD=sonar
     - MYSQL_DATABASE=sonar
     - MYSQL_USER=sonar
     - MYSQL_PASSWORD=sonar
    networks:
      sonar:
        aliases:
         - sonardb

  sonarqube:
    image: sonarqube
    ports:
     - "80:9000"
     - "1099:1099"
    environment:
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
     - SONARQUBE_JDBC_URL=jdbc:mysql://sonardb:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
    command: 
     #Heap size
     - '-Dsonar.ce.javaOpts=-Xmx1024m'
     
    volumes:
     - sonar_conf:/opt/sonarqube/conf
     - sonar_data:/opt/sonarqube/data
     - sonar_ext:/opt/sonarqube/extensions
    networks:
      sonar:
        aliases:
         - sonarqube
    depends_on:
     - sonardb
    
networks:
  sonar:

volumes:
  mysql_db:
  sonar_conf:
  sonar_data:
  sonar_ext:
  
