version: "3"
services:
  sonarqube:
    image: sonarqube
    ports:
     - "9000:9000"
    environment:
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
     - SONARQUBE_JDBC_URL=jdbc:mysql://db:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    link:
     - db
    restart: always
    networks:
     - sonar
  db:
    image: mariadb
    volumes:
     - data_volume: /var/lib/mysql
    command: --max_allowed_packet=256M
    environment:
     - MYSQL_ROOT_PASSWORD=sonar
     - MYSQL_DATABASE=sonar
     - MYSQL_USER=sonar
     - MYSQL_PASSWORD=sonar
    restart: always
    networks:
     - sonar
     
volumes:
 - data_volume